import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const inter = Poppins({weight:'400', subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`overflow-x-hidden bg-contain bg-center ${inter.className}`} style={{ backgroundImage: 'url(/images/image2.png)' }}>
      <Navbar />
      <div className="text-white">
        {children}
      </div>
      <Footer/>
    </body>
  </html>
  );
}
